spring:
  datasource:
    username: root
    password: password
    url: jdbc:mysql://${DB_IP:localhost}:3306/
  jpa.hibernate.ddl-auto: create-drop

logging:
  level:
    root: WARN
    br.com.kimae.multitenacydemo: DEBUG
    com.mysql: NONE
